Feat/az/validation report UI
Informasjonsforvaltning/dcat-ap-no-validator-gui pull request #11
Opened 2021-01-21 16:34 UTC by azaxarov

2021-01-21 16:35 UTC, azaxarov commented
@valosnah, kunne du lagt inn FDK_BASE_URI for denne appen?

2021-01-22 07:48 UTC, oyvindis commented on src/components/validation-report/index.tsx
> +          <SC.ConformsSummary>
Har du sett om Alert-komponent fra fdk-kit kan brukes her?

2021-01-22 08:16 UTC, oyvindis approved these changes

2021-01-22 08:35 UTC, azaxarov commented on src/components/validation-report/index.tsx
> +          <SC.ConformsSummary>
Ja, Jeff har en PR på det

2021-01-22 13:55 UTC, jeffreiffers requested changes

2021-01-22 14:37 UTC, valosnah commented
> @valosnah, kunne du lagt inn FDK_BASE_URI for denne appen?
Så ikke denne før nå, lagt inn

2021-01-25 16:34 UTC, azaxarov commented on src/components/with-validator/redux/saga.ts
>      yield put(actions.validateRdfFailed(e.message));
Ja, se endringer i catch block

2021-01-25 16:34 UTC, azaxarov commented on package.json
> +    "@apollo/client": "^3.3.7",
Ingenting ennå, men forhåpentligvis kan vi ta den i bruk snart

2021-01-26 10:16 UTC, jeffreiffers requested changes

2021-01-26 10:16 UTC, jeffreiffers commented on src/components/with-validator/redux/saga.ts
> +const { VALIDATOR_API_HOST } = env;
Bruk FDK_BASE_URI isteden.

2021-01-26 14:08 UTC, azaxarov commented on src/components/with-validator/redux/saga.ts
> +const { VALIDATOR_API_HOST } = env;
Her er vi faktisk nødt til å bruke `VALIDATOR_API_HOST`, fordi API URL kan ikke konstrueres med `FDK_BASE_URI`

2021-01-27 08:16 UTC, jeffreiffers commented on src/components/with-validator/redux/saga.ts
> +const { VALIDATOR_API_HOST } = env;
Ja selvfølgelig. Glem det.

2021-01-27 08:23 UTC, jeffreiffers approved these changes

2021-01-27 08:49 UTC, merged