fix: make sure the links in the header stay white
Informasjonsforvaltning/dcat-ap-no-validator-gui pull request #127
Opened 2023-01-20 14:44 UTC by hegeaal

Fix because the links in the header was suddenly dark/not showing 🤔

2023-01-23 08:04 UTC, pooriamehregan requested changes

2023-01-23 08:04 UTC, pooriamehregan commented on src/components/header/styled.ts
> +    color: ${theme.colour(Colour.NEUTRAL, 'N0')} !important;
Burde helst unngå `!important`. Tror dette krever fiks i komponenten som tar prioritet ove denne komponenten.

2023-01-23 13:30 UTC, jeffreiffers approved these changes

2023-01-23 13:30 UTC, jeffreiffers commented on src/components/header/styled.ts
> +    color: ${theme.colour(Colour.NEUTRAL, 'N0')} !important;
https://github.com/fellesdatakatalog/fdk-kit/issues/200

2023-01-24 12:21 UTC, hegeaal commented
@jeffreiffers @pooriamehregan Skal jeg bare lukke denne PR'en da?

2023-01-24 12:44 UTC, pooriamehregan commented
@hegeaal Hm, jeg tror du kan lukke det ja.

2023-01-24 12:48 UTC, closed without merging