fix: parse and display blank nodes
Informasjonsforvaltning/dcat-ap-no-validator-gui pull request #43
Opened 2021-04-06 12:36 UTC by jeffreiffers

Fixes #42

2021-04-06 14:45 UTC, azaxarov reviewed
Jeg forstår ikke helt hva dette skal løse. Dessuten tenker jeg at det bør være en bedre måte å løse dette på.

2021-04-08 14:05 UTC, azaxarov requested changes

2021-04-08 14:43 UTC, jeffreiffers commented on src/components/validation-report/utils.ts
> +) =>
Hva mener du med overskrevet?

2021-04-08 14:44 UTC, jeffreiffers commented on src/components/validation-report/utils.ts
> +export const defaultTipGroup = 'andre tips';
Det er det man ønsker. Ja stemmer at det er ikke opprinnelig issuet men dette er et ønske fra stig å gruppere alt som ikke kan knyttes til entity i en slik gruppe

2021-04-08 14:47 UTC, azaxarov commented on src/components/validation-report/utils.ts
> +export const defaultTipGroup = 'andre tips';
Her er det kun snakk om at disse eksportene er ikke nødvendige, men selve default gruppene kan oppgis der grupperingsfunksjonen er eksekvert

2021-04-09 08:27 UTC, azaxarov approved these changes

2021-04-09 08:27 UTC, azaxarov commented on src/components/validation-report/utils.ts
> +) => Object.entries(validationResults)[0][1][0].entityTypes;
Her kan det være enklere med `Object.values()`

2021-04-09 08:55 UTC, jeffreiffers commented on src/components/validation-report/utils.ts
> +) => Object.entries(validationResults)[0][1][0].entityTypes;
Ja, me fiks!!

2021-04-12 08:56 UTC, merged