feat: setup github workflow files
Informasjonsforvaltning/dcat-ap-no-validator-gui pull request #5
Opened 2021-01-11 13:06 UTC by jeffreiffers

2021-01-11 14:20 UTC, valosnah requested changes

2021-01-11 14:20 UTC, valosnah commented on .github/workflows/deploy-staging.yaml
> +          author_name: 'Application: dataset-catalogue-gui | Environment: staging'
Endre til dcat-ap-no-validator-gui

2021-01-12 14:56 UTC, azaxarov requested changes

2021-01-12 14:56 UTC, azaxarov commented on .github/workflows/deploy-staging.yaml
> +          author_name: 'Application: dataset-catalogue-gui | Environment: staging'
Denne står fortsatt som `dataset-catalogue-gui`

2021-01-12 14:56 UTC, azaxarov commented on nginx.conf
> +        try_files $uri $uri/ /index.html;
Her kan vi oppnå samme effekt ved å legge til `rewrite ^/validator(.*) /$1 break;` rett før try_files

2021-01-12 14:56 UTC, azaxarov commented on src/entrypoints/main/router/index.tsx
> +      <BrowserRouter basename={ROUTE_BASE_NAME}>{children}</BrowserRouter>
Gjerne ikke bruk basename. Den har noen rare konsekvenser på URL: https://github.com/ReactTraining/react-router/issues/6226

2021-01-12 14:56 UTC, azaxarov commented on src/env.ts
> +    ROUTE_BASE_NAME: '/',
I stedet for den, så er det et par ting som bør endres i webpack:
1) i base config, sett `publicPath: '/validator'`
2) i samme base config, sett htmlwebpackplugin base til `base: '/validator',`
3) i dev config, bruk `rewrites: [{ from: /./, to: '/validator/index.html' }]` under `historyApiFallback`
4) i prod config, ta bort `publicPath`, den blir da satt i `base.config.ts`

2021-01-13 10:46 UTC, azaxarov approved these changes

2021-01-13 11:40 UTC, closed without merging