Feature/jr/add validator api v2
Informasjonsforvaltning/dcat-ap-no-validator-gui pull request #6
Opened 2021-01-14 14:35 UTC by jeffreiffers

2021-01-15 08:45 UTC, azaxarov requested changes

2021-01-15 08:45 UTC, azaxarov commented on src/utils/commons/index.ts
> +const readFileAsDataURL = async (file: File) => {
rename til `readFileAsText`

2021-01-15 08:45 UTC, azaxarov commented on src/utils/commons/index.ts
> +  return fileContent;
`fileContent` trenger ikke en egen variabel, kan returnere med en gang

2021-01-15 08:45 UTC, azaxarov commented on src/types/domain.d.ts
> +}
```suggestion
export interface ValidationReport {
  conforms: boolean;
  result?: ValidationResult[];
}
```

2021-01-15 08:45 UTC, azaxarov commented on src/types/domain.d.ts
> +  resultSeverity: any;
severity kan gjøres om til enum:
```
export enum Severity {
  VIOLATION = 'Violation',
  WARNING = 'Warning',
  INFO = 'Info'
}
```

2021-01-15 08:45 UTC, azaxarov commented on src/types/domain.d.ts
> +  resultSeverity: any;
Resterende felter kan gjøres om til strngs, er jeg nesten sikker på

2021-01-15 08:45 UTC, azaxarov commented on src/types/domain.d.ts
> +  resource: RdfResource;
`RdfResource` er strengt tatt ikke nødvendig, kan forenkles til `File | url`

2021-01-15 08:45 UTC, azaxarov commented on src/redux/saga.ts
> +import { all } from 'redux-saga/effects';
Det finnes allerede redux setup i `src/entrypoints/main/redux`. Flytt gjerne logikken der

2021-01-15 08:45 UTC, azaxarov commented on src/redux/rootReducer.js
> +import { combineReducers } from 'redux';
Det finnes allerede redux setup i `src/entrypoints/main/redux`. Flytt gjerne logikken der

2021-01-15 08:45 UTC, azaxarov commented on src/entrypoints/main/router/validator/pages/validator-page/index.tsx
> +  console.log(isValidating, errorOccured);
Ta bort console.log

2021-01-15 08:45 UTC, azaxarov commented on src/components/with-validator/index.tsx
> +    errorOccured: state.ValidatorReducer.get('errorOccured') ?? false
`?? false` trengs ikke på begge. Verdien skal alltid være definert

2021-01-15 08:45 UTC, azaxarov commented on package.json
> +    "redux-thunk": "^2.3.0",
disse nye redux middlewares kan vel slettes siden de aldri er i bruk

2021-01-15 08:45 UTC, azaxarov commented on package.json
> +    "buffer": false
Ta denne bort hvis ikke det er noe effekt

2021-01-15 08:45 UTC, azaxarov commented on src/api/validator-api/host.ts
> +import axios from 'axios';
Denne filstrukturen tatt fra portal er litt uheldig synes jeg. Jeg hadde flyttet denne til `src/components/with-validator/redux/operations.ts` og heller hatt API kommunikasjon så nær tilhørende redux som mulig

2021-01-15 08:45 UTC, azaxarov commented on src/api/validator-api/validator.ts
> +// eslint-disable-next-line @typescript-eslint/no-var-requires
Som regel, aldri bruk inline lint disable, heller fix problemet

2021-01-15 08:45 UTC, azaxarov commented on src/components/validation-input-form/index.tsx
> +  onValidate: (file: File | null) => void;
`File | string`

2021-01-15 08:45 UTC, azaxarov commented on package.json
> +    "multipart-mixed-parser": "^0.1.3",
Obscur bibliotek, hadde vurdert to ganger før jeg tok den inn

2021-01-15 08:45 UTC, azaxarov commented on src/entrypoints/main/router/validator/pages/validator-page/index.tsx
> +  const isLoading = false;
Kan bruke isValidating her

2021-01-15 08:45 UTC, azaxarov commented on src/redux/configureStore.js
> +import { createStore, applyMiddleware } from 'redux';
Tror ikke denne filen er i bruk

2021-01-18 09:41 UTC, azaxarov approved these changes

2021-01-18 09:41 UTC, azaxarov commented on package.json
> +    "redux-thunk": "^2.3.0",
gjelder fortsatt

2021-01-18 09:41 UTC, azaxarov commented on package.json
> +    "buffer": false
gjelder fortsatt

2021-01-18 09:41 UTC, azaxarov commented on src/components/with-validator/redux/api.ts
> +import * as RDF from 'rdflib';
Bruk named imports, ellers risikerer vi å dra med hele biblioteket

2021-01-18 09:41 UTC, azaxarov commented on src/types/domain.d.ts
> +  resultSeverity: any;
gjelder fortsatt

2021-01-18 09:41 UTC, azaxarov commented on src/types/domain.d.ts
> +  resource: RdfResource;
gjelder fortsatt

2021-01-18 10:29 UTC, jeffreiffers commented on src/types/domain.d.ts
> +  resource: RdfResource;
File | url eller File | string som du har i input form?

2021-01-18 10:31 UTC, azaxarov commented on src/types/domain.d.ts
> +  resource: RdfResource;
woops, beklager skrivefeil! Skal være `File | string`

2021-01-18 13:08 UTC, closed without merging